ManageSieve for Everyone
python-discord/infra pull request #504
Opened 2024-08-26 17:19 UTC by jchristgit

A spectre is haunting Python Discord -- the spectre of proprietary mail
filtering programs. All the Powers of Big Mail have entered into a holy
alliance to exorcise this spectre: Outlook and GMail, Yahoo and Zoho,
AOL adn iCloud.

Where is the open protocol in opposition that has not been decried as
unprofessional, free and open source by its opponents in power? Where is
the Opposition that has not hurled back the branding reproach of
Internet Standards, against the more advanced opposition protocols, as
well as against its reactionary adversaries?

Two things result from this fact.

I.  Sieve is already standardized as a protocol via the IETF.

II. It is high time that Python Discord users should openly, in the face
of the TLS-encrypted internet, filter their notifications, their love
letters, their mailing lists, and meet this nursery tale of the Spectre
of ManageSieve with a Manifesto of Python Discord Devops itself.

To this end, ManageSieve users of various nationalities have assembled
on jitsi.pydis.wtf, and sketched the following commit, to be published
on the lovelace Python Discord e-mail service.

2024-08-26 20:24 UTC, jb3 requested changes

2024-08-26 20:24 UTC, jb3 commented on docs/docs/services/email/mail-clients.md
> +listing of clients, see [the official Sieve website](sieve.info/clients.).
This link renders wrong, also, sieve.info only works over HTTP:
```suggestion
listing of clients, see [the official Sieve website](http://sieve.info/clients).
```

2024-08-26 20:24 UTC, jb3 commented on ansible/roles/dovecot/templates/dovecot.conf.j2
> -
I'm sure there is a reason, but why is this diff removed?

2024-08-27 00:06 UTC, MarkKoz reviewed
Have I understood correctly that our mail server already supports sieve, but we were merely blocking it in our firewall?

We're using Dovecot, so do we have the [sieve plugin](https://doc.dovecot.org/2.3/configuration_manual/sieve/#sieve) already installed and configured?

2024-08-27 00:26 UTC, jb3 commented
> Have I understood correctly that our mail server already supports sieve, but we were merely blocking it in our firewall?

Correct, it came in the Dovecot PR but we didn't enable it.

> We're using Dovecot, so do we have the [sieve plugin](https://doc.dovecot.org/2.3/configuration_manual/sieve/#sieve) already installed and configured?

Yes, Sieve is installed and configured. By default, it's looking for config in the `~/sieve` file. I don't know if this PR needs us to specify the additional parameters in the Sieve user attribute for ManageSieve support (i.e. `active`)

2024-08-28 02:00 UTC, jb3 requested changes
Works great.

Can we recommend https://github.com/thsmi/sieve as a client as well as sieve-connect?

I've tried this myself and not only does it work great but it also has a nice graphical overview of rule processing which might be easier for non-technical users (as well as of course allowing for manual sieve editing).

2024-08-30 14:58 UTC, jb3 approved these changes

2024-08-30 15:07 UTC, closed without merging